site_name: Swarm Summer School 2026
site_description: Documentation for assembling, configuring, and testing algorithms on our drone platform.

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - Hardware:
    - Overview: hardware/index.md
    - Bill of Materials: hardware/bom.md
    - System Architecture: hardware/architecture.md
    - Expected Assembly: hardware/expected_assembly.md
    - Assembly:
      - Assembly Flowchart: hardware/assembly/flowchart.md
      - Welding Guide: hardware/assembly/welding.md
      - Nipping & Wiring: hardware/assembly/nipping.md
      - Motor Mounting: hardware/assembly/motors.md
      - Frame Assembly: hardware/assembly/frame.md
  - Integration:
    - Overview: integration/index.md
    - Connection Guide: integration/connection_guide.md
    - Bind with Remote Control: integration/remote_control.md
    - RC Setup Simulator: integration/betaflight_simulator.md
    - Communication Links: integration/communication_links.md
  - Software & Configuration:
    - Mission Planner: software/firmware.md
    - QGroundControl Setup: software/qgroundcontrol.md
    - Companion Computer: software/companion_computer.md
  - Checklist:
    - End-to-End Checklist: checklist/index.md
  - Algorithm Testing:
    - Simulation: algorithms/simulation.md
    - Architectures: algorithms/architectures.md
    - Real Hardware Deployment: algorithms/deployment.md
  - Advanced Middleware:
    - DroneManager: middleware/index.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
